package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.domain.TypeObjet;
import ca.ulaval.glo2004.gui.util.ObjetAjoutable;
import ca.ulaval.glo2004.gui.util.ObjetAjoutableTransferHandler;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class BoiteAOutils extends JPanel {
    private final int LARGEUR_INITIALE_OBJETS = 100;
    private final int HAUTEUR_INITIALE_OBJETS = 150;
    
    private final TypeObjet[] typesAjoutables = {TypeObjet.Separateur, TypeObjet.Fenetre, TypeObjet.Porte, TypeObjet.PriseElectrique, TypeObjet.RetourAir};
    
    private List<ObjetAjoutable> objets;
    
    public BoiteAOutils() {
        initComponents();
        
        initialiserObjetsAjoutables();
    }
    
    public void changerVueSelectionne(Vue vue, boolean estVueInterieur) {
        switch(vue) {
            case Salle:
                afficherTypes(new TypeObjet[] {TypeObjet.Separateur, TypeObjet.RetourAir});
                break;
            case Cote:
                if(estVueInterieur) {
                    afficherTypes(typesAjoutables);
                } else {
                    afficherTypes(new TypeObjet[] {TypeObjet.Separateur, TypeObjet.Fenetre, TypeObjet.Porte});
                }
                
                break;
            case Panneau:
                afficherTypes(new TypeObjet[] { });
                break;
        }
    }
    
    private void afficherTypes(TypeObjet[] types) {
        for(ObjetAjoutable objet : objets) {
            objet.setVisible(false);
        }
        
        for(TypeObjet type : types) {
            for(ObjetAjoutable objet : objets) {
                if(objet.getType() == type) {
                    objet.setVisible(true);
                    break;
                }
            }
        }
    }
    
    private void initialiserObjetsAjoutables() {
        objets = new ArrayList<>();
        
        for(TypeObjet type : typesAjoutables) {
            ObjetAjoutable nouvelObjet = creerObjetAjoutable(type);
            
            objets.add(nouvelObjet);
            panneauObjets.add(nouvelObjet);
        }
    }
    
    private ObjetAjoutable creerObjetAjoutable(TypeObjet type) {
        Image image = obtenirImage("/images/" + type.toString().toLowerCase() + ".png");
        
        ObjetAjoutable objet = new ObjetAjoutable(image, type, type.toString());
        
        objet.setPreferredSize(new Dimension(LARGEUR_INITIALE_OBJETS, HAUTEUR_INITIALE_OBJETS));
        objet.setTransferHandler(new ObjetAjoutableTransferHandler());
        
        return objet;
    }
        
    private Image obtenirImage(String path) {
        Image image = null;
        
        URL imageUrl = getClass().getResource(path);
        
        try {
            if(imageUrl != null) {
                image = ImageIO.read(imageUrl);
            }
        } catch (IOException e) {
            System.err.println(path + " : " + e);
        }
        
        return image;     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panneauObjets = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(500, 150));
        setLayout(new java.awt.BorderLayout());

        panneauObjets.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPane.setViewportView(panneauObjets);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panneauObjets;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    public enum Vue {
        Salle,
        Cote,
        Panneau
    }
}
